server {
    # Handle ACME challenge and redirect everything else to HTTPS
    listen 80;
    listen [::]:80;

    server_name connect.womenemerging.org;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host/$request_uri;
    }
}

# server {
#     # redirect no subdomain to www
#     listen [::]:443;
#     listen 443;
#     ssl_certificate /home/ubuntu/.acme.sh/cjrprivate.com_ecc/fullchain.cer;
#     ssl_certificate_key /home/ubuntu/.acme.sh/cjrprivate.com_ecc/cjrprivate.com.key;
#     server_name cjrprivate.com;
#     return 301 https://www.cjrprivate.com$request_uri;
# }

# server {
#     listen                  443 ssl;
#     listen                  [::]:443 ssl;
#     server_name wehub.cjrprivate.com;
#     ssl_certificate /home/ubuntu/.acme.sh/wehub.cjrprivate.com_ecc/fullchain.cer;
#     ssl_certificate_key /home/ubuntu/.acme.sh/wehub.cjrprivate.com_ecc/wehub.cjrprivate.com.key;
#     client_max_body_size 64M;
#
#     location / {
#         proxy_pass "http://localhost:3000/";
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";
#         proxy_set_header X-Forwarded-Proto https;
#         proxy_set_header X-Forwarded-Server $host;
#         proxy_set_header Host $http_host;
#     }
#
#     location ~ /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }
#
#     error_page   500 502 503 504  /50x.html;
# }